version: 0.2

env:
  variables:
    AWS_REGION: us-east-2
    ECR_REPO: aivle-bookservice-frontend
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - echo "ðŸ” ECR ë¡œê·¸ì¸"
      - aws ecr get-login-password --region $AWS_REGION |
        docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo "ðŸ³ Docker ì´ë¯¸ì§€ ë¹Œë“œ"
      - docker build -t $ECR_REPO:$IMAGE_TAG .
      - docker tag $ECR_REPO:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG

  post_build:
    commands:
      - echo "ðŸ“¤ ECRì— ì´ë¯¸ì§€ í‘¸ì‹œ"
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
      - echo "ðŸš€ ë°°í¬ íŒŒì¼ ì¤€ë¹„"
      - printf '[{"name":"backend","imageUri":"%s"}]' \
        $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
